### ISSUE TITLE
ackee 3.0 update

### ISSUE THREAD

**Issue by productdevbook** [oakify/ngx-ackee-wrapper#1]
We updated to 3.0 and no data was seen. Could this be related to the library? It needs to be updated for 3.0 miles.

https://github.com/electerious/Ackee/releases/tag/v3.0.2

**Comment by oakify** [comment]
Thanks for this. Yes it was related to the library. There were a few breaking changes in the newer versions.
That's now fixed in ngx-ackee-wrapper v1.0.0 but🚨lookout🚨for some of our own breaking changes in ngx-ackee-wrapper now that it's in v1.0.0.
Cheers 🍻
